### ISSUE TITLE
Are the build still done?

### ISSUE THREAD

**Issue by ptitSeb** [Itai-Nelken/box86-2deb-weekly-script#4]
I had this ticket https://github.com/ptitSeb/box86/issues/696 that is using this build but end up with a very old release. Is the build still done and on what frequency?

**Comment by Itai-Nelken** [comment]
The builds are still done once a week.
You can see the last build was 6 days ago as of writing this [here](https://github.com/Itai-Nelken/weekly-box86-debs/commit/54aead78f0003d28662ce79e0090d581e29260ab).

**Comment by ptitSeb** [comment]
Ok. Strange that they end up with a very old version of box86. I don't really explain that.

**Comment by Itai-Nelken** [comment]
I just ran an `apt update` and `apt upgrade` and I did get the latest build.
I haven't changed anything in the repo in over a year, so I have no idea why the @nixguru in https://github.com/ptitSeb/box86/issues/696 had an old version.

Can this issue be closed?

**Comment by ptitSeb** [comment]
Yep, thx for testing.

**Comment by dennis1248** [comment]
This issue still seems to be relevant, I also received this same old build when following the instructions for pulling the pre-compiled debs.
```
dennis@pine:~$ box86 -v
Box86 with Dynarec v0.2.3 3a7cc57f built on Jul  9 2021 17:31:35
```

**Comment by Itai-Nelken** [comment]
I think I found the problem: there is an old deb marked as `arm64` instead of `armhf`, so when you install the `box86` package on an arm64 system, that old package will be installed.
Installing `box86:armhf` should fix the problem.

@dennis1248 try removing `box86` and then installing `box86:armhf`.

**Comment by dennis1248** [comment]
@Itai-Nelken Thank you, installing the `:armhf` variant indeed solved the problem.

**Comment by Itai-Nelken** [comment]
great!

As I have moved the scripts to the [apt repo git repo](https://github.com/Itai-Nelken/weekly-box86-debs), I am archiving this repository. So if the need arises to reopen this issue, please do so in that repository.
