### ISSUE TITLE
How do I specify an old version of libc and libm when compiling box86

### ISSUE THREAD

**Issue by ccfxny** [Itai-Nelken/box86-2deb-weekly-script#5]
Hello, wen I make box86 on a Phytium machine,
when me used this script to make box86's deb
Unable to run wine application in wine
Because wine's lib.so.6=libc-2.28.so
But when I make, the version of lbc.so in my Phytium system was equal to =2.3.1, so the operation went wrong.
i want to ask
How do I specify an old version of libc and libm when compiling box86, for example, I use /lib/arm-linux-gnueabihf/libc.so.6

box86: /lib/arm-linux-gnueabihf/libm,so.6: version 'GLIBC 2.29' not found
box86: /lib/arm-linux-gnueabihf/libc,so.6: version 'GLIBC 2.33
/box86: /lib/arm-linux-gnueabihf/libc.so.6: version 'GLIBC 2.32
/box86: /lib/arm-linux-gnueabihf/libc.so.6: version 'GLIBC 2.34

**Comment by ccfxny** [comment]
Your version of armhf has not been updated for a long time, so I tried to compile it myself
But i have this libc problem can't handle
Or I can try to compile your same version of armhf? I can only compile the arm64 version on my computer.

**Comment by Itai-Nelken** [comment]
I'm not sure I understood you correctly, so correct me if I answer the wrong question.
My repository is [here](https://github.com/Itai-Nelken/weekly-box86-debs), and it automatically updates weekly.
You can try using the packages from the repo, they are compiled with glibc 2.27.
You can also try compiling yourself.
In any case you will need armhf multiarch to use box86.
